frontend/models/CmTargetResult.php
<?php

namespace frontend\models;

use common\models\BaseActiveRecord;
use Yii;
use yii\behaviors\AttributesBehavior;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "cm_target_result".
 *
 * @property int $tg_id
 * @property string $tg_date วันที่คัดกรอง
 * @property int $tg_target_id กลุ่มเป้าหมาย
 * @property string $tg_amphur อำเภอ
 * @property int $tg_num เป้าหมาย
 * @property int $tg_rs ได้รับการประเมิน
 * @property int $tg_l1 เครียดมาก
 * @property int $tg_l2 มีแนวโน้มซึมเศร้า
 * @property int $tg_l3 ซึมเศร้า
 * @property int $tg_l4 เสี่ยงฆ่าตัวตาย
 * @property int $tg_l5 ติดตาม
 * @property string|null $created_at วันที่บันทึก
 * @property string|null $updated_at วันที่บันทึก
 * @property string|null $updated_user วันที่บันทึก
 * @property int|null $created_user ผู้บันทึก
 *
 * @property Amphur $tgAmphur
 * @property CmTarget $target
 * @property \common\models\User $createdUser
 */
class CmTargetResult extends BaseActiveRecord
{
    public $_tggroupname;
    public $targetnames;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cm_target_result';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tg_date', 'tg_amphur','tg_target_id','tg_num', 'tg_rs', 'tg_l1', 'tg_l2', 'tg_l3', 'tg_l4', 'tg_l5'], 'required'],
            [['tg_num', 'tg_rs', 'tg_l1', 'tg_l2', 'tg_l3', 'tg_l4', 'tg_l5'],'default','value' => 0],
            [['tg_date', 'created_at','updated_at','updated_by'], 'safe'],
            [['tg_target_id','tg_num', 'tg_rs', 'tg_l1', 'tg_l2', 'tg_l3', 'tg_l4', 'tg_l5', 'created_user'], 'number','min'=>0],
            [['tg_amphur'], 'string', 'max' => 6],

            [['tg_amphur'], 'exist', 'skipOnError' => true, 'targetClass' => Amphur::className(), 'targetAttribute' => ['tg_amphur' => 'ampurcodefull']],

            [['tg_target_id','tg_date','tg_amphur'],'unique','targetAttribute' => ['tg_target_id', 'tg_date','tg_amphur'],'message' => 'มีการบันทึกข้อมูลในวันที่นี้แล้ว'],

            [['tg_target_id'], 'exist', 'skipOnError' => true, 'targetClass' => CmTarget::className(), 'targetAttribute' => ['tg_target_id' => 'targetgroup_id']],

            [['created_user'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_user' => 'id']],
            [['tg_rs', 'tg_l1', 'tg_l2', 'tg_l3', 'tg_l4', 'tg_l5'],'compare','compareAttribute' => 'tg_num','operator' => '<=','type' => 'number','enableClientValidation' => false],
            [['_tggroupname','_tg_date1','_tg_date2','targetnames'],'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'tg_id' => 'Tg ID',
            'tg_target_id' => 'กลุ่มเป้าหมาย',
            'tg_date' => 'วันที่คัดกรอง',
            'tg_amphur' => 'อำเภอ',
            'tg_num' => 'เป้าหมาย',
            'tg_rs' => 'ได้รับการประเมิน',
            'tg_l1' => 'เครียดมาก',
            'tg_l2' => 'มีแนวโน้มซึมเศร้า',
            'tg_l3' => 'ซึมเศร้า',
            'tg_l4' => 'เสี่ยงฆ่าตัวตาย',
            'tg_l5' => 'ติดตาม',
            'created_at' => 'วันที่บันทึก',
            'update_at' => 'วันที่บันทึก',
            'created_user' => 'ผู้บันทึก',
            'updated_user' => 'ผู้บันทึก',
            '_tg_date1'=>'เริ่มต้น',
            '_tg_date2'=>'สิ้นสุด',
            'targetnames'=>'กลุ่มเป้าหมาย'
        ];
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new \yii\db\Expression('NOW()'),
            ],
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_user',
                'updatedByAttribute' => 'updated_user',
            ],
        ];
    }

    /**
     * Gets query for [[TgAmphur]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTgAmphur()
    {
        return $this->hasOne(Amphur::className(), ['ampurcodefull' => 'tg_amphur']);
    }

    /**
     * Gets query for [[CreatedUser]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_user']);
    }

    /**
     * Gets query for [[CreatedUser]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTarget()
    {
        return $this->hasOne(\frontend\models\CmTarget::className(), ['targetgroup_id' => 'tg_target_id']);
    }

    public function getTargetnames(){
        return $this->target->targetname;
    }
}

frontend/controllers/CmTargetResultController.php
<?php

namespace frontend\controllers;

use common\models\Document;
use common\models\ProjectPayment;
use frontend\models\Amphur;
use frontend\models\CmTarget;
use Yii;
use frontend\models\CmTargetResult;
use frontend\models\CmTargetResultSearch;
use yii\base\Model;
use yii\bootstrap4\ActiveForm;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * CmTargetResultController implements the CRUD actions for CmTargetResult model.
 */
class CmTargetResultController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['*'],
                'rules' => [
                    [
                        'actions' => [ 'index','create', 'update', 'delete', 'check-update', 'validate-create-target',  'deletefile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index','view',],
                        'allow' => true,
                        'roles' => ['?'],
                    ],

                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CmTargetResult models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CmTargetResultSearch();
        $searchModel->scenario = 'searchTg';
        $dataProvider = $searchModel->searchReportPv(Yii::$app->request->queryParams);
        $amp = Amphur::getMukAmphur(1);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'amp'=>$amp
        ]);
    }

    /**
     * Displays a single CmTargetResult model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCheckUpdate($d,$a){
        // check old data
        $check = CmTargetResult::find()->where(['tg_amphur' => $a, 'tg_date' => $d])->exists();
        if($check){
            //$cmTarget = CmTarget::getList();
            $targetModels = [];
            $models = CmTargetResult::find()->select(['cm_target_result.*','cm_target.targetname'])->joinWith('target')->where(['tg_amphur' => $a, 'tg_date' => $d])->indexBy('tg_target_id')->all();
            foreach ($models as $index => $item){
//            echo $item.$index;
                $targetModels[$index] = $item;
            }
            $html = $this->renderAjax('_update',[
                //'model' => $model,
                'targetRsModels'=>$targetModels,
                'd'=>$d,
                'a'=>$a
            ]);
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'status'=>true,
                'message'=>$html
            ];
        }else{
            $cmTarget = CmTarget::getList();
            $targetModels = [];
            foreach ($cmTarget as $index => $item){
//            echo $item.$index;
                $m = new CmTargetResult();
                $m->tg_target_id = $index;
                $m->_tggroupname = $item;
                $m->tg_num = 0;
                $m->tg_rs = 0;
                $m->tg_l1 = 0;
                $m->tg_l2 = 0;
                $m->tg_l3 = 0;
                $m->tg_l4 = 0;
                $m->tg_l5 = 0;
                $targetModels[] = $m;
            }

            $amphurModel = Amphur::getMukAmphur();

            $html =  $this->renderAjax('_create', [
                //'model' => $model,
                'targetRsModels'=>$targetModels,
                'd'=>$d,
                'a'=>$a
                //'amphurModel'=>$amphurModel
            ]);
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'status'=>false,
                'message'=>$html
            ];
        }
    }

    /**
     * Creates a new CmTargetResult model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CmTargetResult();
        $flag = Yii::$app->request->post('flag');
        if($flag=='new'){
            if (Yii::$app->request->post() && Yii::$app->request->isAjax) {
                $data = Yii::$app->request->post('CmTargetResult',[]);
                //print_r($data);
                $date = $data['tg_date'];
                $amphur = $data['tg_amphur'];

                ArrayHelper::remove($data,'tg_date');
                ArrayHelper::remove($data,'tg_amphur');

                foreach (array_keys($data) as $index) {
                    $a = new CmTargetResult();
                    $a->tg_date = $date;
                    $a->tg_amphur = $amphur;
                    $a->created_user = Yii::$app->user->id;
                    $models[$index] = $a;
                }

                Model::loadMultiple($models, Yii::$app->request->post());
                if(Model::validateMultiple($models)) {
                    $ts = Yii::$app->db->beginTransaction();
                    try {
                        $success = 0;
                        foreach ($models as $model) {
                            $model->tg_date = $date;
                            $model->tg_amphur = $amphur;
                            $model->created_user = Yii::$app->user->id;
                            if($model->validate() &&$model->save()){
                                $success++;
                            }else{
                                throw new Exception(implode(',',$model->getErrorSummary(true)));
                            }

                        }
                        $ts->commit();
                        Yii::$app->response->format = Response::FORMAT_JSON;
                        return [
                            'status'=>true,
                            'message'=>'บันทึกข้อมูลสำเร็จ'
                        ];
                    }catch (\Exception $exception){
                        Yii::$app->response->format = Response::FORMAT_JSON;
                        return [
                            'status'=>false,
                            'message'=>'ไม่สามารถบันทึกข้อมูลได้ เนื่องจาก '.$exception->getMessage()
                        ];
                    }
                }else{
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return [
                        'status'=>false,
                        'message'=>'ไม่สามารถบันทึกข้อมูลได้'
                    ];
                }
            }
        }elseif($flag=='update'){
            if (Yii::$app->request->post() && Yii::$app->request->isAjax) {
                $data = Yii::$app->request->post('CmTargetResult',[]);
                //print_r($data);
                $date = $data['tg_date'];
                $amphur = $data['tg_amphur'];

                ArrayHelper::remove($data,'tg_date');
                ArrayHelper::remove($data,'tg_amphur');

                $models = CmTargetResult::find()->where(['tg_amphur' => $amphur, 'tg_date' => $date])->indexBy('tg_target_id')->all();

                /*foreach (array_keys($data) as $index) {
                    $a = new CmTargetResult();
                    $a->tg_date = $date;
                    $a->tg_amphur = $amphur;
                    $a->created_user = Yii::$app->user->id;
                    $models[$index] = $a;
                }*/

                Model::loadMultiple($models, Yii::$app->request->post());

                //var_dump($models);

                if(Model::validateMultiple($models)) {
                    $ts = Yii::$app->db->beginTransaction();
                    try {
                        $success = 0;
                        foreach ($models as $model) {
                            if($model->validate() &&$model->save()){
                                $success++;
                            }else{
                                throw new Exception(implode(',',$model->getErrorSummary(true)));
                            }

                        }
                        $ts->commit();
                        Yii::$app->response->format = Response::FORMAT_JSON;
                        return [
                            'status'=>true,
                            'message'=>'อัพเดทข้อมูลสำเร็จ'
                        ];
                    }catch (\Exception $exception){
                        Yii::$app->response->format = Response::FORMAT_JSON;
                        return [
                            'status'=>false,
                            'message'=>'ไม่สามารถอัพเดทข้อมูลได้ เนื่องจาก '.$exception->getMessage()
                        ];
                    }
                }else{
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return [
                        'status'=>false,
                        'message'=>'ไม่สามารถอัพเดทข้อมูลได้'
                    ];
                }
            }
        }


        ////////////////////////////////////////////////////////////////////////////
        $cmTarget = CmTarget::getList();
        $targetModels = [];
        /*foreach ($cmTarget as $index => $item){
//            echo $item.$index;
            $m = new CmTargetResult();
            $m->tg_target_id = $index;
            $m->_tggroupname = $item;
            $m->tg_num = 0;

frontend/views/cm-target-result/_create.php
<?php
/* @var $targetRsModels frontend\models\CmTargetResult[] */

use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$form = \yii\bootstrap4\ActiveForm::begin([
//        'layout' => '',
    'id' => 'create-cm-target',
    'validateOnSubmit' => true,
    'validateOnBlur' => false,
    'validateOnChange' => false,
    'enableAjaxValidation' => true,
    //'layout' => 'horizontal',
    'validationUrl' => Url::to(['validate-create-target']),
    'options' => [
        'class' => 'kt-form kt-form--fit kt-form--label-right',
        //'enctype' => 'multipart/form-data',
    ],
]);


?>

<table id="cmtargettable" class="table table-hover table-bordered table-striped">
    <thead>
    <tr>
        <th style="white-space: nowrap; min-width: 250px;">กลุ่มเป้าหมาย</th>
        <th style="white-space: nowrap; min-width: 70px;">เป้าหมาย</th>
        <th style="white-space: nowrap; min-width: 70px;">ได้รับการประเมิน</th>
        <th style="white-space: nowrap; min-width: 70px;">เครียดมาก</th>
        <th style="white-space: nowrap; min-width: 70px;">มีแนวโน้มซึมเศร้า</th>
        <th style="white-space: nowrap; min-width: 70px;">ซึมเศร้า</th>
        <th style="white-space: nowrap; min-width: 70px;">เสี่ยงฆ่าตัวตาย</th>
        <th style="white-space: nowrap; min-width: 70px;">ติดตาม</th>
    </tr>
    </thead>
    <tbody>
    <?php
    echo Html::hiddenInput('flag','new',['id'=>'flag']);
    echo Html::hiddenInput('CmTargetResult[tg_date]',$d,['id'=>'CmTargetResult[tg_date]']);
    echo Html::hiddenInput('CmTargetResult[tg_amphur]',$a,['id'=>'CmTargetResult[tg_amphur]']);

    foreach ($targetRsModels as $index => $targetRsModel) {
        ?>
        <?= Html::activeHiddenInput($targetRsModel, "[$index]tg_target_id") ?>
        <?= Html::activeHiddenInput($targetRsModel, "[$index]tg_id") ?>
        <tr>
            <td width="30%;"><?= $form->field($targetRsModel, "[$index]_tggroupname")->textInput(['disabled' => true])->label(false) ?></td>
            <td><?= $form->field($targetRsModel, "[$index]tg_num")->textInput(['type' => 'number'])->label(false) ?></td>
            <td><?= $form->field($targetRsModel, "[$index]tg_rs")->textInput(['type' => 'number'])->label(false) ?></td>
            <td><?= $form->field($targetRsModel, "[$index]tg_l1")->textInput(['type' => 'number'])->label(false) ?></td>
            <td><?= $form->field($targetRsModel, "[$index]tg_l2")->textInput(['type' => 'number'])->label(false) ?></td>
            <td><?= $form->field($targetRsModel, "[$index]tg_l3")->textInput(['type' => 'number'])->label(false) ?></td>
            <td><?= $form->field($targetRsModel, "[$index]tg_l4")->textInput(['type' => 'number'])->label(false) ?></td>
            <td><?= $form->field($targetRsModel, "[$index]tg_l5")->textInput(['type' => 'number'])->label(false) ?></td>
        </tr>

        <?php echo Html::activeHiddenInput($targetRsModel, "[$index]created_user"); ?>
        <?php
    }
    ?>
    </tbody>
</table>

<div class="form-group">
    <div class="col-md-10 offset-2">
        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
        <?= Html::resetButton('ยกเลิก', ['class' => 'btn btn-danger']) ?>
    </div>
</div>
<?php
ActiveForm::end();
?>

frontend/views/cm-target-result/_form.php
<?php

use kartik\date\DatePicker;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model frontend\models\CmTargetResult */
/* @var $amphurModel frontend\models\Amphur[] */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $targetRsModels frontend\models\CmTargetResult[] */

\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos' => \yii\web\View::POS_END,]);

?>


<div class="kt-portlet__body">

    <?php $form = \yii\bootstrap4\ActiveForm::begin([
//        'layout' => '',
        'id' => 'create-cm-target-search',
        'validateOnSubmit' => true,
        'validateOnBlur' => false,
        'validateOnChange' => false,
        'enableAjaxValidation' => true,
        //'layout' => 'horizontal',
        'validationUrl' => Url::to(['validate-create-target']),
        'options' => [
            'class' => 'kt-form kt-form--fit kt-form--label-right',
            //'enctype' => 'multipart/form-data',
        ],
    ]);

    //var_dump($targetRsModels);
    ?>
    <div class="form-group row form-group-marginless kt-margin-t-20">
        <div class="col-lg-4">
            <?= $form->field($model, 'tg_date')->widget(
                DatePicker::className(), [
                'language' => 'th',
                'options' => ['placeholder' => '','autocomplete'=>'off'],
                'pluginOptions' => [
                    'format' => 'yyyy-mm-dd',
                    'autoclose' => true,

                ],
            ]); ?>
        </div>
        <div class="col-lg-4">
            <?= $form->field($model, 'tg_amphur')->dropDownList($amphurModel) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="form-group row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <div id="data">

                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/cm-target-result/_script.php
<?php

use yii\helpers\Url; ?>
<script>
    var body = $(document);
    var submitForm = function () {
        body.on("beforeSubmit", "form#create-cm-target", function (e) {
            e.preventDefault();
            e.isImmediatePropagationStopped();

            //var form = document.getElementById('baseForm');
            var formData = new FormData($(this)[0]);
            //var flag = $("#flag").val();


            swal.fire({
                title: 'ยืนยันการบันทึกข้อมูล',
                text: "ตรวจสอบความถูกต้องของข้อมูล!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'ยืนยันการบันทึก'
            }).then(function (result) {
                if (result.value) {
                    KTApp.blockPage();
                    $.ajax({
                        cache: false,
                        contentType: false,
                        processData: false,
                        url: $(this).attr("action"),
                        type: "post",
                        data: formData,//form.serialize(),
                        success: function (response) {
                            KTApp.unblockPage();
                            // do something with response
                            console.log(response);
                            //response = JSON.parse(response);
                            swal.fire(
                                'ผลการบันทึก!',
                                response.message,
                                (response.status == true) ? "success" : "warning"
                            );
                            if (response.status == true) {
                                //$("form#create-cm-target")[0].reset();
                            }
                        },
                        complete: function () {
                            KTApp.unblockPage();
                        },
                        error: function (error) {
                            KTApp.unblockPage();
                        }
                    });
                }
            });
            return false;
        });
    };

    var checkUpdate = function () {
        body.on("change", "#cmtargetresult-tg_date", function (e) {
            e.preventDefault();
            e.isImmediatePropagationStopped();

            var d = $("#cmtargetresult-tg_date").val();
            var amp = $("#cmtargetresult-tg_amphur").val();
            console.log(d, amp);
            if(amp!=''){
                //swal.fire('แจ้งเตือน','load data','warning')
                loadData(d,amp);
            }
        });

        body.on("change", "#cmtargetresult-tg_amphur", function (e) {
            e.preventDefault();
            e.isImmediatePropagationStopped();

            var d = $("#cmtargetresult-tg_date").val();
            var amp = $(this).val();
            console.log(d, amp);
            if(d==''){
                swal.fire('แจ้งเตือน','กรุณาเลือกวันที่','warning')
            }else{
                //swal.fire('แจ้งเตือน','load data','success')
                loadData(d,amp);
            }
        });
    };

    function loadData(d,a){
        KTApp.blockPage();
        $.ajax({
            url: "<?=Url::to(['cm-target-result/check-update','d'=>''])?>"+d+"&a="+a,
            type: "get",
            success: function (response) {
                KTApp.unblockPage();
                if(response.status==true){
                    swal.fire("แจ้งเตือน",'พบข้อมูลเดิมที่เคยบันทึกแล้ว หากกดบันทึกจะทำการแก้ไขข้อมูลเก่าที่เคยรายงาน','warning');
                    $("#data").html(response.message);
                }else{
                    $("#data").html(response.message);
                }
            },
            complete: function () {
                KTApp.unblockPage();
            },
            error: function (error) {
                KTApp.unblockPage();
            }

        });
    };

    $(function () {
        submitForm();
        checkUpdate();
    });
</script>

frontend/views/cm-target-result/_search.php
<?php

use kartik\date\DatePicker;
use kartik\daterange\DateRangePicker;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model frontend\models\CmTargetResultSearch */
/* @var $form yii\bootstrap4\ActiveForm */
?>

<div class="cm-target-result-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        //'layout' => 'horizontal',
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <?= $form->field($model, 'tg_amphur')->dropDownList($amp) ?>
        </div>
        <div class="col-lg-4 col-md-6">
            <?= $form->field($model, 'tg_date',[
                //'addon'=>['prepend'=>['content'=>'<i class="fas fa-calendar-alt"></i>']],
                'options'=>['class'=>'drp-container form-group',]
            ])->widget(
                DateRangePicker::classname(), [
                'pluginOptions'=>[
                    'locale'=>[
                        'separator'=>' ถึง ',
                    ],
                    'opens'=>'left'
                ],
                'options'=>[
                    'autocomplete'=>'off'
                ]
                //'useWithAddon'=>true
            ])->label('ช่วงวันที่คัดกรอง'); ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('ดูรายงาน', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('ยกเลิก',Url::to(['index']), ['class' => 'btn btn-warning']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

frontend/views/cm-target-result/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\CmTargetResult */
/* @var $amphurModel frontend\models\Amphur[] */
/* @var $targetRsModels frontend\models\CmTargetResult[] */

$this->title = 'รายงานผลการคัดกรอง';
$this->params['breadcrumbs'][] = ['label' => 'คัดกรองเยียวยาด้านจิตใจ', 'url' => ['index'],'class' => 'kt-subheader__breadcrumbs-link'];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' =>'#' ,'class' => 'kt-subheader__breadcrumbs-link'];
?>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            <?= Html::encode($this->title) ?>
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->

                <?= $this->render('_form', [
                    'model' => $model,
                    'targetRsModels'=>$targetRsModels,
                    'amphurModel'=>$amphurModel
                ]) ?>

                <!--end::Form-->
            </div>
        </div>

    </div>
</div>

frontend/views/cm-target-result/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\CmTargetResult */

$this->title = 'Update Cm Target Result: ' . $model->tg_id;
$this->params['breadcrumbs'][] = ['label' => 'Cm Target Results', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->tg_id, 'url' => ['view', 'id' => $model->tg_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cm-target-result-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>