common/models/MeetingResponsible.php
<?php

namespace common\models;

use Yii;
use \common\models\base\MeetingResponsible as BaseMeetingResponsible;
use yii\db\Exception;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\web\HttpException;

/**
 * This is the model class for table "meeting_responsible".
 */
class MeetingResponsible extends BaseMeetingResponsible
{
    /**
     * @inheritdoc
     */
   /* public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['mission_id', 'item_id', 'responsible_status', 'responsible_user'], 'integer'],
            [['item_id', 'responsible_status'], 'required'],
            [['updated_date'], 'safe'],
            [['mission_id', 'item_id'], 'unique', 'targetAttribute' => ['mission_id', 'item_id'], 'message' => 'The combination of ผู้รับผิดขอบ and รายละเอียด has already been taken.']
        ]);
    }*/


    public static function saveRes($models,$pk,$flag='new'){
        //var_dump($models);
        //echo $pk;
        $rows = [];
        if(empty($models))
            return false;

        if ($flag == 'new') {
            foreach ($models as $model) {
                $rows[] = [$pk, $model, 1, new Expression('NOW()')];
            }

            //var_dump($rows);
            $command = Yii::$app->db->createCommand();
            $command->batchInsert(self::tableName(),
                ['item_id', 'mission_id', 'responsible_status', 'updated_date'],
                $rows
            );
            try {
                return $command->execute();
            } catch (Exception $exception) {
                throw new Exception($exception->getMessage());
            }
        } elseif ($flag == 'update') {
            $oldModel = self::findAll(['item_id' => $pk]);
            $oldId = ArrayHelper::getColumn($oldModel, 'mission_id'); // รายการเก่า
            $cId = $models; // รายการใหม่
            $deleteIds = array_diff($oldId, $cId);
            $insertIds = array_diff($cId, $oldId);
            if ($deleteIds) {
                self::deleteAll(['and', 'item_id = :item_id',['in','mission_id',$deleteIds]],[':item_id'=>$pk]);
               // self::updateAll(['deleted_by' => Yii::$app->user->id, 'deleted_at' => new Expression('NOW()')], ['and', 'prj_id = :prj_id', ['in', 'dep_id', $deleteIds]], [':prj_id' => $pk]);
            }
            if ($insertIds) {
                foreach ($insertIds as $id) {
                    $rows[] = [$pk, $id, 1, new Expression('NOW()')];
                }
                $command = Yii::$app->db->createCommand();
                $command->batchInsert(self::tableName(),
                    ['item_id', 'mission_id', 'responsible_status', 'updated_date'],
                    $rows
                );

                try {
                    return $command->execute();
                } catch (Exception $exception) {
                    throw new Exception($exception->getMessage());
                }
            }
        }
    }

    public function meetingResponsibleStyle(){
        if ($this->responsible_status == 1) {
            $style = 'warning';
        } elseif ($this->responsible_status == 2) {
            $style = 'success';
        }elseif ($this->responsible_status == 3) {
            $style = 'dark line-through';
        }elseif ($this->responsible_status == 4) {
            $style = 'secondary text-danger';
        }elseif ($this->responsible_status == 0) {
            $style = 'danger blink';
        }

        $urgency = "<div class='badge badge-{$style}'>" . self::getResponsibleStatusItem($this->responsible_status) ."  </div>";
        return $urgency;
    }

    public function meetingResponsibleMissionStyle(){
        if ($this->responsible_status == 1) {
            $style = 'warning';
        } elseif ($this->responsible_status == 2) {
            $style = 'success';
        }elseif ($this->responsible_status == 3) {
            $style = 'dark';
        }elseif ($this->responsible_status == 4) {
            $style = 'danger';
        }elseif ($this->responsible_status == 0) {
            $style = 'danger';
        }

        $urgency = "<font class='text-{$style}'>".$this->mission->mission_name . " (".self::getResponsibleStatusItem($this->responsible_status) .")  </font>";
        return $urgency;
    }
	
}

frontend/controllers/MeetingResponsibleController.php
<?php

namespace frontend\controllers;

use common\models\MeetingCommandItems;
use common\models\MeetingCommandLog;
use common\models\MeetingReport;
use common\models\MeetingResponsible;
use frontend\models\MeetingResponsibleSearch;
use Yii;
use yii\bootstrap4\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\BaseFileHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * MeetingResponsibleController implements the CRUD actions for MeetingResponsible model.
 */
class MeetingResponsibleController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all MeetingResponsible models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MeetingResponsibleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MeetingResponsible model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $providerMeetingCommandLog = new \yii\data\ArrayDataProvider([
            'allModels' => $model->meetingCommandLogs,
        ]);
        $providerMeetingReport = new \yii\data\ArrayDataProvider([
            'allModels' => $model->meetingReports,
        ]);
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
            'providerMeetingCommandLog' => $providerMeetingCommandLog,
            'providerMeetingReport' => $providerMeetingReport,
        ]);
    }

    /**
     * Finds the MeetingResponsible model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MeetingResponsible the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MeetingResponsible::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new MeetingResponsible model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * id of meetingcommanditem
     *
     */
    public function actionCreate($id, $mission_id = null)
    {
        $model = MeetingResponsible::find()->where('mission_id=:mission and item_id=:item', [
            ':mission' => $mission_id, ':item' => $id,
        ])->one();
        $reportModel = new MeetingReport();
        //$model->scenario = 'create-report';
        //$model->item_id = $id;
        //$model->mission_id = $mission_id;
        if ($model->load(Yii::$app->request->post()) && $reportModel->load(Yii::$app->request->post())) {
            $ts = Yii::$app->db->beginTransaction();
            try {
                $this->CreateDir($reportModel->report_path_temp, 'report_path_temp');
                $reportModel->report_file = $this->uploadMultipleFile($reportModel, null, 'report_file');
                $reportModel->report_images = $this->uploadMultipleFile($reportModel, null, 'report_images');

                $log = new MeetingCommandLog();
                $log->old_status = $model->getOldAttribute('responsible_status');
                $log->new_status = $model->responsible_status;

                if ($model->save()) {
                    //$pk = $model->getPrimaryKey();
                    $reportModel->responsible_id = $model->responsible_id;
                    $reportModel->report_date = $model::dateEngDb($reportModel->report_date);
                    $reportModel->save();

                    $log->report_id = $reportModel->getPrimaryKey();
                    $log->responsible_id = $model->responsible_id;
                    $log->updated_at = new Expression('NOW()');
                    $log->save();

                    //var_dump($log->getErrorSummary(true));

                    $ts->commit();
                    return Json::encode([
                        'title' => 'ผลการบันทึก',
                        'message' => 'บันทึกข้อมูลสำเร็จ',
                        'status' => 'success',
                        'url' => Url::to(['meeting/view', 'id' => $mission_id]),
                    ]);
                } else {
                    $ts->rollBack();
                    $error = $model->getErrorSummary(true);
                    return Json::encode([
                        'title' => 'ผลการบันทึกข้อมูล',
                        'message' => 'พบข้อผิดพลาด ไม่สามารถบันทึกข้อมูลได้ เนื่องจาก' . implode(',', $error),
                        'status' => 'error',
                    ]);
                }

                //return $this->redirect(['project/index']);
            } catch (\Exception $exception) {
                $ts->rollBack();
                $message = $exception->getMessage();
                return Json::encode([
                    'title' => 'ผลการบันทึก',
                    'message' => 'พบข้อผิดพลาด ไม่สามารถบันทึกข้อมูลได้ เนื่องจาก' . $message,
                    'status' => 'error',
                ]);
            }
        } else {
            $commandItem = MeetingCommandItems::findOne($id);

            $reportProvider = new ActiveDataProvider();
            $reportModel->report_path_temp = substr(Yii::$app->getSecurity()->generateRandomString(), 10);
            return $this->renderAjax('create', [
                'model' => $model,
                'item' => $commandItem,
                'reportModel' => $reportModel,
            ]);
        }
    }

    public function actionCreateStag($id, $mission_id = null)
    {

        $reportModel = new MeetingReport();
        $reportModel->scenario = 'create-stag';
        //$model->scenario = 'create-report';
        //$model->item_id = $id;
        //$model->mission_id = $mission_id;
        if (Yii::$app->request->isPost && $reportModel->load(Yii::$app->request->post())){
            $model = MeetingResponsible::findOne($reportModel->_responsible_id);

            $ts = Yii::$app->db->beginTransaction();
            try {
                $this->CreateDir($reportModel->report_path_temp, 'report_path_temp');
                $reportModel->report_file = $this->uploadMultipleFile($reportModel, null, 'report_file');
                $reportModel->report_images = $this->uploadMultipleFile($reportModel, null, 'report_images');

                $model->responsible_status = $reportModel->_responsible_status;
                $model->updated_date = new Expression('NOW()');

                $log = new MeetingCommandLog();
                $log->old_status = $model->getOldAttribute('responsible_status');
                $log->new_status = $model->responsible_status;



                if ($model->save()) {
                    //$pk = $model->getPrimaryKey();
                    $reportModel->responsible_id = $model->responsible_id;
                    $reportModel->report_date = $model::dateEngDb($reportModel->report_date);
                    $reportModel->save();

                    $log->report_id = $reportModel->getPrimaryKey();
                    $log->responsible_id = $model->responsible_id;
                    $log->updated_at = new Expression('NOW()');
                    $log->save();

                    //var_dump($log->getErrorSummary(true));

                    $ts->commit();
                    return Json::encode([
                        'title' => 'ผลการบันทึก',
                        'message' => 'บันทึกข้อมูลสำเร็จ',
                        'status' => 'success',
                        'url' => Url::to(['meeting/view', 'id' => $mission_id]),
                    ]);
                } else {
                    $ts->rollBack();
                    $error = $model->getErrorSummary(true);
                    return Json::encode([
                        'title' => 'ผลการบันทึกข้อมูล',
                        'message' => 'พบข้อผิดพลาด ไม่สามารถบันทึกข้อมูลได้ เนื่องจาก' . implode(',', $error),
                        'status' => 'error',
                    ]);
                }

                //return $this->redirect(['project/index']);
            } catch (\Exception $exception) {
                $ts->rollBack();
                $message = $exception->getMessage();
                return Json::encode([
                    'title' => 'ผลการบันทึก',
                    'message' => 'พบข้อผิดพลาด ไม่สามารถบันทึกข้อมูลได้ เนื่องจาก' . $message,
                    'status' => 'error',
                ]);
            }
        } else {
            $model = MeetingResponsible::find()->joinWith('mission')->select([
                'responsible_id',
                'meeting_responsible.mission_id','mission_name','item_id','responsible_status'
            ])->where('item_id=:item', [
               ':item' => $id,
            ])->all();
            $commandItem = MeetingCommandItems::findOne($id);


            $reportModel->report_path_temp = substr(Yii::$app->getSecurity()->generateRandomString(), 10);
            return $this->renderAjax('createStag', [
                'model' => $model,
                'item' => $commandItem,
                'reportModel' => $reportModel,
            ]);
        }
    }

    private function CreateDir($folderName, $attribute = 'report_path_temp')
    {
        //echo $folderName;

frontend/views/meeting-responsible/_form.php
<?php

use common\models\MeetingCommandItems;
use kartik\date\DatePicker;
use marqu3s\summernote\Summernote;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\MeetingResponsible */
/* @var $form yii\widgets\ActiveForm */
/* @var $reportModel common\models\MeetingReport */
/* @var $item common\models\MeetingCommandItems */

/*\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END,
    'viewParams' => [
        'class' => 'MeetingCommandLog', 
        'relID' => 'meeting-command-log', 
        'value' => \yii\helpers\Json::encode($model->meetingCommandLogs),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MeetingReport', 
        'relID' => 'meeting-report', 
        'value' => \yii\helpers\Json::encode($model->meetingReports),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);*/
?>

<div class="meeting-responsible-form">

    <?php $form = \yii\bootstrap4\ActiveForm::begin([
        'id' => 'create-meeting-responsible',
        'validateOnSubmit' => true,
        'validateOnBlur' => false,
        'validateOnChange' => false,
        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
        'validationUrl' => Url::to(['validate-meeting-responsible']),
        'options' => [
            'class' => 'kt-form kt-form--fit kt-form--label-right',
            'enctype' => 'multipart/form-data',
        ],
    ]);


    echo Html::activeHiddenInput($model, 'responsible_id');
    echo Html::activeHiddenInput($model, 'mission_id');
    echo Html::activeHiddenInput($model, 'item_id');
    echo Html::activeHiddenInput($reportModel, 'report_id');
    echo Html::activeHiddenInput($reportModel, 'report_path_temp');
    //echo Html::activeHiddenInput($reportModel, 'images_tmp');
    ?>

    <div class="well-sm"><h4><?=$item->item_detail?></h4></div>
    <div class="row">
        <div class="col-sm-12">
            <?= $form->field($reportModel, 'report_detail')->widget(Summernote::className(),[]) ?>
        </div>

        <div class="col-sm-6">
            <?= $form->field($reportModel, 'report_file[]')->widget(\kartik\widgets\FileInput::className(), [
                'language' => 'th',
                'options' => [
                    'multiple' => true,
                ],
                'pluginOptions' => [
                    'showPreview' => true,
                    'showRemove' => true,
                    'showUpload' => false,
                    'overwriteInitial' => true,
                    'autoReplace' => true,
                    'uploadUrl' => Url::to(['meeting-responsible/create']),
                ],
                //''
            ]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($reportModel, 'report_images[]')->widget(\kartik\widgets\FileInput::className(), [
                'language' => 'th',
                'options' => [
                    'multiple' => true,
                ],
                'pluginOptions' => [
                    'showPreview' => true,
                    'showRemove' => true,
                    'showUpload' => false,
                    'overwriteInitial' => true,
                    'autoReplace' => true,
                    'uploadUrl' => Url::to(['meeting-responsible/create']),
                ],
                //''
            ]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($reportModel, 'report_date')->widget(DatePicker::className(), [
                'options' => [
                    'autocomplete' => "off",
                ],
                'pluginOptions' => [
                    'format' => 'dd-mm-yyyy',
                    'todayHighlight' => true,
                    'size' => 'xs',
                    'autoclose' => true,
                ],
            ]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($model, 'responsible_status')->dropDownList($model::getResponsibleStatusList()) ?>
        </div>
    </div>
    <!--<div class="row">
        <div class="col-sm-12">
        <?php
/*        $forms = [
            [
                'label' => '<i class="fa fa-file"></i> ' . Html::encode('ประวัติการรายงาน'),
                'content' => $this->render('_viewMeetingReport', [
                    'row' => \yii\helpers\ArrayHelper::toArray($model->meetingReports),
                ]),
            ],
        ];
        echo kartik\tabs\TabsX::widget([
            'items' => $forms,
            'position' => kartik\tabs\TabsX::POS_ABOVE,
            'encodeLabels' => false,
            'pluginOptions' => [
                'bordered' => true,
                'sideways' => true,
                'enableCache' => false,
            ],
        ]);
        */?>
        </div>
    </div>-->

    <?= $form->errorSummary([$model, $reportModel]); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'บันทึก' : 'บันทึก', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/meeting-responsible/_formMeetingCommandLog.php
<div class="form-group" id="add-meeting-command-log">
<?php
use kartik\grid\GridView;
use kartik\builder\TabularForm;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\widgets\Pjax;

$dataProvider = new ArrayDataProvider([
    'allModels' => $row,
    'pagination' => [
        'pageSize' => -1
    ]
]);
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'MeetingCommandLog',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        'log_id' => ['type' => TabularForm::INPUT_TEXT],
        'old_status' => ['type' => TabularForm::INPUT_TEXT],
        'new_status' => ['type' => TabularForm::INPUT_TEXT],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return
                    Html::hiddenInput('Children[' . $key . '][id]', (!empty($model['id'])) ? $model['id'] : "") .
                    Html::a('<i class="glyphicon glyphicon-trash"></i>', '#', ['title' =>  'Delete', 'onClick' => 'delRowMeetingCommandLog(' . $key . '); return false;', 'id' => 'meeting-command-log-del-btn']);
            },
        ],
    ],
    'gridSettings' => [
        'panel' => [
            'heading' => false,
            'type' => GridView::TYPE_DEFAULT,
            'before' => false,
            'footer' => false,
            'after' => Html::button('<i class="glyphicon glyphicon-plus"></i>' . 'Add Meeting Command Log', ['type' => 'button', 'class' => 'btn btn-success kv-batch-create', 'onClick' => 'addRowMeetingCommandLog()']),
        ]
    ]
]);
echo  "    </div>\n\n";
?>

frontend/views/meeting-responsible/_formStag.php
<?php

use kartik\date\DatePicker;
use kartik\grid\GridView;
use marqu3s\summernote\Summernote;
use yii\bootstrap4\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\MeetingResponsible */
/* @var $form yii\widgets\ActiveForm */
/* @var $reportModel common\models\MeetingReport */
/* @var $item common\models\MeetingCommandItems */

/*\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END,
    'viewParams' => [
        'class' => 'MeetingCommandLog', 
        'relID' => 'meeting-command-log', 
        'value' => \yii\helpers\Json::encode($model->meetingCommandLogs),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MeetingReport', 
        'relID' => 'meeting-report', 
        'value' => \yii\helpers\Json::encode($model->meetingReports),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);*/
?>

<div class="meeting-responsible-form">

    <?php $form = \yii\bootstrap4\ActiveForm::begin([
        'id' => 'create-meeting-responsible-stag',
        'validateOnSubmit' => true,
        'validateOnBlur' => false,
        'validateOnChange' => false,
        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
        'validationUrl' => Url::to(['validate-meeting-responsible-stag']),
        'options' => [
            'class' => 'kt-form kt-form--fit kt-form--label-right',
            'enctype' => 'multipart/form-data',
        ],
    ]);


    //echo Html::activeHiddenInput($model, 'responsible_id');
    //echo Html::activeHiddenInput($model, 'mission_id');
    //echo Html::activeHiddenInput($model, 'item_id');
    echo Html::activeHiddenInput($reportModel, 'report_id');
    echo Html::activeHiddenInput($reportModel, 'report_path_temp');
    //echo Html::activeHiddenInput($reportModel, 'images_tmp');


    //$mission_ids = ArrayHelper::getColumn($model,'mission_id');
    $list = ArrayHelper::merge([''=>'เลือกผู้รับผิดชอบ'],ArrayHelper::map($model,'responsible_id','mission.mission_name'))
    ?>

    <div class="well well-sm">
        <h4><?= $item->item_detail ?></h4>
        <p>กลุ่มงาน/กล่องภารกิจ ที่เกี่ยวข้อง</p>
        <?php
        $responsible = new ActiveDataProvider([
            'models' => $model,
            'pagination' => false,
        ]);
        $gridColumn = [
            /*[
                'class' => '\yii\grid\RadioButtonColumn',
                'radioOptions' => function ($model) {
                    return [
                        'value' => $model['responsible_id'],
                        'id'=> "meetingreport-{$model['responsible_id']}-_responsible_id",
                        'name'=>'MeetingReport[_responsible_id]'
                    ];
                },
                'contentOptions' => [
                    'class' => 'text-center',
                ],
                'name' => 'MeetingReport[_responsible_id]',
            ],*/
            [
                'attribute' => 'mission_id',
                'value' => function ($model) {
                    return $model->mission->mission_name;
                },
            ], [
                'attribute' => 'responsible_status',
                'label' => 'สถานะการดำเนินการ',
                'value' => function ($model) {
                    return $model->meetingResponsibleStyle();
                },
                'format' => 'raw',
            ],
        ];
        echo Gridview::widget([
            'dataProvider' => $responsible,
            'pjax' => true,
            'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-meeting-command']],
            'panel' => false,
            'export' => false,
            'columns' => $gridColumn,
        ]);
        ?>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <?= $form->field($reportModel, 'report_detail')->widget(Summernote::className(), []) ?>
        </div>

        <div class="col-sm-6">
            <?= $form->field($reportModel, 'report_file[]')->widget(\kartik\widgets\FileInput::className(), [
                'language' => 'th',
                'options' => [
                    'multiple' => true,
                ],
                'pluginOptions' => [
                    'showPreview' => true,
                    'showRemove' => true,
                    'showUpload' => false,
                    'overwriteInitial' => true,
                    'autoReplace' => true,
                    'uploadUrl' => Url::to(['meeting-responsible/create']),
                ],
                //''
            ]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($reportModel, 'report_images[]')->widget(\kartik\widgets\FileInput::className(), [
                'language' => 'th',
                'options' => [
                    'multiple' => true,
                ],
                'pluginOptions' => [
                    'showPreview' => true,
                    'showRemove' => true,
                    'showUpload' => false,
                    'overwriteInitial' => true,
                    'autoReplace' => true,
                    'uploadUrl' => Url::to(['meeting-responsible/create']),
                ],
                //''
            ]) ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($reportModel, '_responsible_id')->dropDownList($list) ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($reportModel, '_responsible_status')->dropDownList($reportModel::getResponsibleStatusList()) ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($reportModel, 'report_date')->widget(DatePicker::className(), [
                'options' => [
                    'autocomplete' => "off",
                ],
                'pluginOptions' => [
                    'format' => 'dd-mm-yyyy',
                    'todayHighlight' => true,
                    'size' => 'xs',
                    'autoclose' => true,
                ],
            ]) ?>
        </div>
    </div>
    <!--<div class="row">
        <div class="col-sm-12">
        <?php
    /*        $forms = [
                [
                    'label' => '<i class="fa fa-file"></i> ' . Html::encode('ประวัติการรายงาน'),
                    'content' => $this->render('_viewMeetingReport', [
                        'row' => \yii\helpers\ArrayHelper::toArray($model->meetingReports),
                    ]),
                ],
            ];
            echo kartik\tabs\TabsX::widget([
                'items' => $forms,
                'position' => kartik\tabs\TabsX::POS_ABOVE,
                'encodeLabels' => false,
                'pluginOptions' => [
                    'bordered' => true,
                    'sideways' => true,
                    'enableCache' => false,
                ],
            ]);
            */ ?>
        </div>
    </div>-->

    <?= $form->errorSummary([$reportModel]); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'บันทึก' : 'บันทึก', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/meeting-responsible/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

frontend/views/meeting-responsible/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\MeetingResponsible */
/* @var $item common\models\MeetingCommandItems */
/* @var $reportModel common\models\MeetingReport */

$this->title = 'รายงานข้อสั่งการ ';

?>
<div class="meeting-responsible-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'item'=>$item,
        'reportModel'=>$reportModel
    ]) ?>

</div>