common/models/DocumentType.php
<?php

namespace common\models;

use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "document_type".
 *
 * @property int $doctype_id
 * @property string $doctype_name ประเภทเอกสาร
 * @property string|null $doctype_icon ไอคอน
 *
 * @property Document[] $documents
 */
class DocumentType extends BaseActiveRecord
{
    public $tot_doc;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'document_type';
    }

    public static function getList()
    {
        $list = self::find()->select(['doctype_name', 'doctype_id'])->all();
        return ArrayHelper::map($list, 'doctype_id', 'doctype_name');
    }

    /**
     * {@inheritdoc}
     * @return DocumentTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DocumentTypeQuery(get_called_class());
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doctype_name'], 'required'],
            [['doctype_name'], 'string', 'max' => 255],
            [['doctype_icon'], 'string', 'max' => 50],
            ['tot_doc', 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'doctype_id' => 'Doctype ID',
            'doctype_name' => 'ประเภทเอกสาร',
            'doctype_icon' => 'ไอคอน',
            'tot_doc' => 'ประเภทเอกสาร',
        ];
    }

    /**
     * Gets query for [[Documents]].
     *
     * @return \yii\db\ActiveQuery|DocumentQuery
     */
    public function getDocuments()
    {
        return $this->hasMany(Document::className(), ['document_type' => 'doctype_id']);
    }
}

frontend/controllers/DocumentController.php
<?php

namespace frontend\controllers;

use common\models\Document;
use common\models\Project;
use frontend\models\DocumentSearch;
use Yii;
use yii\bootstrap4\ActiveForm;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\BaseFileHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;
use ZipArchive;

/**
 * DocumentController implements the CRUD actions for Document model.
 */
class DocumentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['*'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view', 'download-zip', 'validate-create-document',  'deletefile', 'download'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['view', 'download-zip', 'download',],
                        'allow' => true,
                        'roles' => ['?'],
                    ],

                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Document models.
     * @return mixed
     */
    public function actionIndex($id = null, $type = null)
    {
//        echo $id;
//        echo $type;
        $searchModel = new DocumentSearch();
        $searchModel->mission_id = $id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Document model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionViewFile($id){
        /*$model = $this->findModel($id);
        if (!empty($model->{$type})) {
            Yii::$app->response->sendFile($model->getUploadPath($type) . '/' . $model->files_path . '/' . $file, $file_name, ['inline' => true]);
        }*/
    }

    /**
     * Finds the Document model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Document the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Document::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Document model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($type, $mission)
    {

        $model = new Document();

        $model->files_path = substr(Yii::$app->getSecurity()->generateRandomString(), 10);
        if ($model->load(Yii::$app->request->post())) {
            $this->CreateDir($model->files_path, 'files');
            $model->files = $this->uploadMultipleFile($model, null, 'files');

            if ($model->save()) {
                return Json::encode([
                    'title' => 'ผลการบันทึกข้อมูล',
                    'message' => 'บันทึกข้อมูลเอกสารสำเร็จ',
                    'status' => 'success',
                    'url' => Url::to(['document/index']),
                ]);
            } else {
                $error = $model->getErrorSummary(true);
                return Json::encode([
                    'title' => 'ผลการบันทึกข้อมูล',
                    'message' => 'พบข้อผิดพลาดในการบันทึกข้อมูลเอกสาร ' . implode(',', $error),
                    'status' => 'error',
                    'url' => Url::to(['document/index']),
                ]);
            }
        }

        $model->document_type = $type;
        $model->mission_id = $mission;

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    private function CreateDir($folderName, $attribute = 'files')
    {
        //echo $folderName;
        $basePath = Document::getUploadPath($attribute);
        if ($folderName != null && !is_dir($basePath . $folderName)) {

            //echo $basePath;
            BaseFileHelper::createDirectory($basePath . $folderName, 0777);
//            if (BaseFileHelper::createDirectory($basePath . $folderName, 0777)) {
//                BaseFileHelper::createDirectory($basePath . $folderName . '/thumbnail', 0777);
//            }else{

            //}
            //echo $basePath . $folderName;
        }
        //echo $folderName;
        return;
    }

    private function uploadMultipleFile($model, $tempFile = null, $attribute)
    {
        //echo $attribute;
        $files = [];
        $json = '';
        $tempFile = Json::decode($tempFile);
        $UploadedFiles = UploadedFile::getInstances($model, $attribute);

//        print_r($UploadedFiles);
//        print_r($tempFile);

        if ($UploadedFiles !== null) {
            foreach ($UploadedFiles as $file) {
                try {
                    $oldFileName = $file->basename . '.' . $file->extension;
                    $newFileName = md5($file->basename . time()) . '.' . $file->extension;

                    $file->saveAs(Document::getUploadPath($attribute) . $model->{'files_path'} . '/' .
                        $newFileName);

                    //$fileThumbnailPath = Project::getUploadPath($attribute) . $model->{$attribute . '_ref'} . '/thumbnail';

                    /*@Image::getImagine()->open(Project::getUploadPath($attribute) .
                        $model->{$attribute . '_ref'} . '/' . $newFileName)->thumbnail(new Box(120, 120))->save($fileThumbnailPath . '/' . $newFileName, ['quality' => 90]);*/

                    $files[$newFileName] = $oldFileName;
                } catch (\Exception $e) {
                    throw new \Exception($e->getMessage());
                }
            }
            $json = Json::encode(ArrayHelper::merge($tempFile, $files));
        } else {
            $json = $tempFile;
        }
        //echo $json;
        return $json;
    }

    /**
     * Updates an existing Document model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $tempFile = $model->files;
        //$model->files_path = substr(Yii::$app->getSecurity()->generateRandomString(), 10);
        if ($model->load(Yii::$app->request->post())) {
            $this->CreateDir($model->files_path, 'files');
            $model->files = $this->uploadMultipleFile($model, $tempFile, 'files');

            if ($model->save()) {
                return Json::encode([
                    'title' => 'ผลการบันทึกข้อมูล',
                    'message' => 'บันทึกข้อมูลเอกสารสำเร็จ',
                    'status' => 'success',
                    'url' => Url::to(['document/index']),
                ]);
            } else {
                $error = $model->getErrorSummary(true);
                return Json::encode([
                    'title' => 'ผลการบันทึกข้อมูล',
                    'message' => 'พบข้อผิดพลาดในการบันทึกข้อมูลเอกสาร ' . implode(',', $error),
                    'status' => 'error',
                    'url' => Url::to(['document/index']),
                ]);
            }
        }

        //echo $model->files;
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Document model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $ts = Yii::$app->db->beginTransaction();
        try {
            if ($id) {
                $model = Document::deleteAll(['=', 'document_id', $id]);
                $ts->commit();
            } else {
                $ids = Yii::$app->request->post('key');
                if (!is_null($ids)) {
                    $ids = explode(',', $ids);
                    $model = Document::deleteAll(['in', 'document_id', $ids]);
                    $ts->commit();
                }
            }
            return Json::encode([
                'result' => true,
                'msg' => 'ลบข้อมูลเรียบร้อย',
                'options' => [],
            ]);
        } catch (Exception $exception) {
            $ts->rollBack();
            return Json::encode([
                'result' => false,
                'msg' => 'ไม่สามารถลบข้อมูลได้ เนื่องจาก ' . $exception->getMessage(),
                'options' => [],
            ]);
        }
    }

    public function actionValidateCreateDocument()
    {
        $data = Yii::$app->request->post('Document');
        if (null != $data['document_id']) {
            $model = Document::findOne($data['document_id']);

        } else {
            //ถ้าเป็นการบันทึกใหม่ ให้สร้าง โมเดลใหม่
            $model = new Document();
            //$model->scenario = 'insert';
        }
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {

frontend/views/document/_form.php
<?php

use t01\assets\TagsInputAsset;
use common\models\DocumentType;
use kartik\file\FileInput;
use marqu3s\summernote\Summernote;
use mludvik\tagsinput\TagsInputWidget;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Document */
/* @var $form yii\bootstrap4\ActiveForm */

TagsInputAsset::register($this);
?>

<?php $form = ActiveForm::begin([
//        'layout' => '',
    'id' => 'create-document',
    'validateOnSubmit' => true,
    'validateOnBlur' => false,
    'validateOnChange' => false,
    'enableAjaxValidation' => true,
    'validationUrl' => Url::to(['validate-create-document']),
    'options' => [
        'class' => 'kt-form kt-form--fit kt-form--label-right',
        'enctype' => 'multipart/form-data',
    ],
]);

echo Html::activeHiddenInput($model, 'files_path');
echo Html::activeHiddenInput($model, 'mission_id');

?>
    <div class="kt-portlet__body">
        <div class="form-group row form-group-marginless kt-margin-t-20">
            <div class="col-lg-12">
                <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
            </div>
        </div>
        <div class="form-group row form-group-marginless kt-margin-t-20">
            <div class="col-lg-12">
                <?= $form->field($model, 'description')->widget(Summernote::className(), []) ?>
            </div>
        </div>

        <!--<div class="form-group row form-group-marginless kt-margin-t-20">
            <div class="col-lg-12">
                <?/*= $form->field($model, 'document_name')->textInput(['maxlength' => true]) */?>
            </div>
        </div>-->

        <div class="form-group row form-group-marginless kt-margin-t-20">
            <div class="col-lg-3">
                <?= $form->field($model, 'document_type')->dropDownList(DocumentType::getList()) ?>
            </div>
            <div class="col-lg-6">
                <?= $form->field($model, 'tags', [
                    'inputOptions' => ['data-role' => 'tagsinput']
                ])->textInput(['maxlength' => true]) ?>

            </div>
            <div class="col-lg-3">
                <?= $form->field($model, 'status')->radioList(['1' => 'เผยแพร่', '0' => 'จำกัด']) ?>
            </div>
        </div>

        <div class="form-group row form-group-marginless kt-margin-t-20">
            <div class="col-lg-12">
                <?= $form->field($model, 'files')->widget(FileInput::className(), [
                    'language' => 'th',
                    'options' => [
                        'multiple' => true,
                    ],
                    'pluginOptions' => [
                        'showPreview' => true,
                        'showRemove' => true,
                        'showUpload' => false,
                        'overwriteInitial' => true,
                        'autoReplace' => true,
                        'maxFileCount' => 20,
                        'maxFileSize'=>28000
                        //'uploadUrl' => Url::to(['document/create']),
                    ],
                ]) ?>
            </div>
        </div>


        <?php // $form->field($model, 'created_by')->textInput() ?>

        <?php // $form->field($model, 'created_at')->textInput() ?>

        <?php // $form->field($model, 'updated_by')->textInput() ?>

        <?php // $form->field($model, 'updated_at')->textInput() ?>

        <div class="kt-portlet__foot kt-portlet__foot--fit-x">
            <div class="kt-form__actions">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-10">
                        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
                        <?= Html::submitButton('ยกเลิก', ['class' => 'btn btn-warning']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php ActiveForm::end(); ?>


<?php

$this->registerJs("
$(document).on(\"beforeSubmit\", \"form#create-document\", function (e) {
        e.preventDefault();
        e.isImmediatePropagationStopped();

        //var form = document.getElementById('baseForm');
        var formData = new FormData($(this)[0]);
        KTApp.blockPage({
                overlayColor: '#000000',
                type: 'v2',
                state: 'primary',
                message: 'กำลังบันทึกข้อมูล...'
            });
        $.ajax({
                    cache: false,
                    contentType: false,
                    processData: false,
                    url: $(this).attr(\"action\"),
                    type: \"post\",
                    data: formData,//form.serialize(),
                    success: function (response) {
                        // do something with response
                        console.log(response);
                        //unblockUi('blockPanel');
                        response = JSON.parse(response);                      
                       swal.fire(
                            response.title,
                            response.message,
                            response.status
                        );
                        if(response.status=='success'){
                            $(\"form#create-document\")[0].reset();
                        }
                        KTApp.unblockPage();
                    },
                    complete: function () {
                        //unblockUi('blockPanel');
                        KTApp.unblockPage();
                    },
                    error: function (error) {
                        //unblockUi('blockPanel');
                        console.info(error);
                        KTApp.unblockPage();
                    }
                });
        
        return false;
    });
");

?>

frontend/views/document/_search.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\DocumentSearch */
/* @var $form yii\bootstrap\ActiveForm */
?>

    <?php $form = ActiveForm::begin([
        //'layout' => 'inline',
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1,
            'class' => 'kt-form kt-form--label-right',
        ],
    ]); ?>
    <div class="kt-portlet__body">
        <div class="form-group row">
            <div class="col-lg-4">
                <?= $form->field($model, 'title') ?>
            </div>
            <div class="col-lg-4">
                <?= $form->field($model, 'description') ?>
            </div>
            <div class="col-lg-4">
                <?= $form->field($model, 'document_type') ?>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-lg-6">
                <?= $form->field($model, 'tags') ?>
            </div>
            <div class="col-lg-6">
                <?php echo $form->field($model, 'document_name') ?>
            </div>
        </div>

        <?php // echo $form->field($model, 'status') ?>

        <?php // echo $form->field($model, 'has_thumbnail') ?>



        <?php // echo $form->field($model, 'created_by') ?>

        <?php // echo $form->field($model, 'created_at') ?>

        <?php // echo $form->field($model, 'updated_by') ?>

        <?php // echo $form->field($model, 'updated_at') ?>

        <div class="kt-portlet__foot">
            <div class="kt-form__actions">
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-8">
                        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
                        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
                    </div>
                </div>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

frontend/views/document/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Document */

/*
 * $this->params['breadcrumbs'][] = [
    'label' => $this->title,
    'url' => '#',
    'class' => 'kt-subheader__breadcrumbs-link',
];*/

$this->title = 'สร้างเอกสาร';
$this->params['breadcrumbs'][] = ['label' => 'เอกสารทั้งหมด', 'url' => ['index'],'class' => 'kt-subheader__breadcrumbs-link'];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' =>'#' ,'class' => 'kt-subheader__breadcrumbs-link'];
?>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            <?= Html::encode($this->title) ?>
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->

                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>

                <!--end::Form-->
            </div>
        </div>

    </div>
</div>

frontend/views/document/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Document */

$this->title = 'แก้ไขเอกสาร';
$this->params['breadcrumbs'][] = ['label' => 'เอกสารทั้งหมด', 'url' => ['index'],'class' => 'kt-subheader__breadcrumbs-link'];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' =>'#' ,'class' => 'kt-subheader__breadcrumbs-link'];
?>
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            <?= Html::encode($this->title) ?>
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->

                <?= $this->render('_form_update', [
                    'model' => $model,
                ]) ?>

                <!--end::Form-->
            </div>
        </div>

    </div>
</div>

frontend/views/document/view.php
<?php

use yii\bootstrap4\Carousel;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Document */

$this->title = $model->title;

if (Yii::$app->user->isGuest) {
    $this->params['breadcrumbs'][] = ['label' => 'เอกสารทั้งหมด', 'class' => 'kt-subheader__breadcrumbs-link', 'url' => ['site/index-dashboard']];
    $this->params['breadcrumbs'][] = ['label' => $this->title, 'class' => 'kt-subheader__breadcrumbs-link',];
} else {

    $this->params['breadcrumbs'][] = ['label' => 'เอกสารทั้งหมด', 'class' => 'kt-subheader__breadcrumbs-link', 'url' => ['index']];
    $this->params['breadcrumbs'][] = ['label' => $this->title, 'class' => 'kt-subheader__breadcrumbs-link',];
}
\yii\web\YiiAsset::register($this);
?>
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-xl-12">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            <i class="flaticon2-information kt-font-brand"></i> <?= Html::encode($this->title) ?>
                        </h3>
                    </div>
                    <div class="kt-portlet__head-toolbar">
                        <div class="kt-portlet__head-actions">
                            <?php
                            if (Yii::$app->user->id == $model->created_by) :
                                ?>
                                <?= Html::a('<i class="flaticon2-edit"></i>', ['document/update', 'id' => $model->document_id], ['class' => 'btn btn-outline-success btn-sm btn-icon btn-icon-sm']) ?>
                                <?= Html::a('<i class="flaticon2-trash"></i>', ['delete', 'id' => $model->document_id], [
                                'class' => 'btn btn-outline-danger btn-sm btn-icon btn-icon-sm deleteDoc',
                                'data' => [
                                    'confirm' => 'ยืนยันการลบข้อมูลนี้ ?',
                                    'method' => 'post',
                                ],
                            ]) ?>
                            <?php
                            endif;
                            ?>
                        </div>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <!--begin::Section-->
                    <div class="kt-section">
													<span class="kt-section__info">
													</span>
                        <div class="kt-section__content">
                            <div class="table-responsive">

                                <?= DetailView::widget([
                                    'model' => $model,
                                    'template' => '<tr ><th style="width: 20%" {captionOptions}>{label}</th><td{contentOptions}>{value}</td></tr>',
                                    'attributes' => [
//                                        'document_id',
                                        'title',
                                        //'document_name',
                                        'description:raw',
                                        'documentTypeName:raw',
                                        [
                                            'label' => 'เอกสารแนบ',
                                            'format' => 'raw',
                                            'value' => function ($model) {
                                                $a = $model->viewFiles();
                                                //print_r($a[1]);
                                                $carousel = "";
                                                if ($a[1] != []) {
                                                    $c = Carousel::widget([
                                                        'items' =>
                                                        // the item contains only the image
                                                            $a[1],
                                                    ]);

                                                    $carousel = "<div class='col-md-12'><div class=\"kt-portlet kt-portlet--head-noborder\">
                                                        <div class=\"kt-portlet__head\">
                                                            <div class=\"kt-portlet__head-label\">
                                                                <h3 class=\"kt-portlet__head-title  kt-font-danger\">
                                                                    ภาพ
                                                                </h3>
                                                            </div>                                                      
                                                        </div>
                                                        <div class=\"kt-portlet__body kt-portlet__body--fit-top\">
                                                                <div class=\"kt-section kt-section--space-sm\">
                                                                   {$c}
                                                                </div>                                                           
                                                                </div>
                                                            </div>
                                                      </div>";
                                                }

                                                if ($a[0] != "") {
                                                    $files = "<div class='col-md-12'><div class=\"kt-portlet kt-portlet--head-noborder\">
                                                        <div class=\"kt-portlet__head\">
                                                            <div class=\"kt-portlet__head-label\">
                                                                <h3 class=\"kt-portlet__head-title  kt-font-danger\">
                                                                    ดาวน์โหลด
                                                                </h3>
                                                            </div>   
                                                            <div class=\"kt-portlet__head-toolbar\">
                                                                " . Html::a('<i class="flaticon2-download"></i>', ['document/download-zip', 'id' => $model->document_id], ['class' => 'btn btn-outline-danger btn-sm btn-icon btn-icon-sm', 'title' => 'ดาวน์โหลดทั้งหมด', 'target' => '_blank']) . "
                                                            </div>                                                   
                                                        </div>
                                                        <div class=\"kt-portlet__body kt-portlet__body--fit-top\">
                                                                <div class=\"kt-section kt-section--space-sm\">
                                                                   {$a[0]}
                                                                </div>                                                           
                                                                </div>
                                                            </div>
                                                      </div>";
                                                }
                                                //var_dump($a[0]);
                                                return "<div class=\"row\">{$carousel}\t{$files}</div>";
                                            },
                                        ],

                                        'tags',
                                        'statusDoc',
//                                        'has_thumbnail',
                                        [
                                            'label' => 'ผู้บันทึก',
                                            'value' => function ($model) {
                                                return $model->createdBy->getFullname();
                                            },
                                        ],
                                        'created_at:date',
                                        [
                                            'label' => 'ผู้แก้ไข',
                                            'value' => function ($model) {
                                                return $model->updatedBy->getFullname();
                                            },
                                        ],
                                        'updated_at:date',
                                    ],
                                ]) ?>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>